from fastapi import FastAPI, HTTPException, Query
from openai import OpenAI
import requests
import time
import os
from datetime import datetime
import json

# Configurar o cliente OpenAI com a chave correta
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY')
ASSISTANT_ID = os.environ.get('ASSISTANT_ID')
ASSISTANT_ID_GROUP = os.environ.get('ASSISTANT_ID_GROUP')
GOOGLE_API_KEY = os.environ.get('GOOGLE_API_KEY')
cx = os.environ.get('cx')

app = FastAPI()

# Configurar o cliente OpenAI com a chave correta
client = OpenAI(api_key=OPENAI_API_KEY)

# Função para enviar a lista de produtos para a API
def send_products_to_api(products, assistant_id):
    # Criar o thread
    thread = client.beta.threads.create()

    # Adicionar mensagens ao thread
    message = client.beta.threads.messages.create(
        thread_id=thread.id,
        role="user",
        content=f"{products}"
    )

    # Executar o thread com o assistente v2
    run = client.beta.threads.runs.create(
        thread_id=thread.id,
        assistant_id=assistant_id
    )

    # Verificar o status do run até ser concluído
    timeout = 30
    start_time = time.time()
    while run.status != "completed":
        run = client.beta.threads.runs.retrieve(
            thread_id=thread.id,
            run_id=run.id
        )
        time.sleep(0.5)
        if time.time() - start_time > timeout:
            raise HTTPException(status_code=500, detail="Timeout ao executar o thread")

    # Recuperar as mensagens do thread após o run ser completado
    messages = client.beta.threads.messages.list(
        thread_id=thread.id
    )

    # Extrair as informações da resposta do OpenAI
    result = None
    for message in messages:
        for content in message.content:
            if content.text:
                result = content.text.value
                break
        if result:
            break

    # Retornar a última resposta do assistente
    return result

# Endpoint de pesquisa de produtos
@app.get("/search_product/")
def search_product(product_name: str = Query(..., min_length=3, max_length=50)):
    # Realizar pesquisa no Google
    search_results = requests.get(f"https://www.googleapis.com/customsearch/v1?q={product_name}&key={GOOGLE_API_KEY}&cx={cx}").json()

    # Enviar a lista de produtos para a API
    products = search_results.get('items', [])
    result = send_products_to_api(products, ASSISTANT_ID)

    # Retornar a resposta em formato JSON
    return json.loads(result)

# Função para pesquisar produtos por tipo
def search_products_by_type():
    # Lista de tipos de produtos
    product_types = [
    "geladeira",
    "fogão",
    "micro-ondas",
    "lava-louças",
    "máquina de lavar roupa",
    "secadora de roupas",
    "aspirador de pó",
    "air fryer",
    "cafeteira",
    "torradeira",
    "liquidificador",
    "batedeira",
    "ferro de passar",
    "purificador de água",
    "ar-condicionado",
    "ventilador",
    "aquecedor",
    "panela elétrica",
    "grill elétrico",
    "forno elétrico",
    "sanduicheira",
    "fritadeira elétrica",
    "processador de alimentos",
    "coifa",
    "exaustor",
    "máquina de gelo",
    "adega climatizada",
    "máquina de costura",
    "lavadora de alta pressão",
    "cortador de grama",
    "triturador de alimentos",
    "fogão cooktop",
    "forno a gás",
    "bebedouro",
    "desumidificador",
    "umidificador",
    "aspirador robô",
    "chaleira elétrica",
    "espremedor de frutas",
    "sorveteira",
    "panela de arroz",
    "panela de pressão elétrica",
    "máquina de pão",
    "mopa a vapor",
    "purificador de ar",
    "cervejeira",
    "massageador",
    "máquina de crepe",
    "máquina de waffles",
    "forno elétrico de embutir",
    "frigobar",
    "lava e seca",
    "centrífuga de alimentos",
    "cooktop por indução",
    "balança de cozinha",
    "triturador de resíduos",
    "espremedor de alho",
    "faca elétrica",
    "panela wok",
    "panela de fondue",
    "chapas elétricas",
    "sous vide",
    "moedor de café",
    "moinho de grãos",
    "termômetro culinário",
    "purificador de água portátil",
    "balança corporal",
    "difusor de aromas",
    "manta térmica",
    "cadeira de massagem",
    "despertador inteligente",
    "abajur",
    "luminária",
    "papel de parede",
    "cortina",
    "tapete",
    "almofada",
    "cobertor",
    "lençol",
    "travesseiro",
    "colcha",
    "edredom",
    "jogo de cama",
    "toalhas de banho",
    "toalhas de mesa",
    "pratos",
    "talheres",
    "copos",
    "taças",
    "panelas",
    "assadeiras",
    "forma de bolo",
    "jogo de facas",
    "tupperware",
    "fruteira",
    "porta-temperos",
    "porta-copos",
    "caixa organizadora",
    "estante modulada",
    "mesa de cabeceira",
    "cama box",
    "bicama",
    "berço",
    "cama infantil",
    "cama queen size",
    "cama king size",
    "sofa-cama",
    "mesa lateral",
    "escrivaninha infantil",
    "cadeira de escritório",
    "cadeira gamer",
    "gaveteiro",
    "divisória de ambiente",
    "puff",
    "espelho decorativo",
    "porta-retrato",
    "vasos decorativos",
    "relógio de parede",
    "quadros decorativos",
    "papelaria",
    "canetas",
    "lápis",
    "cadernos",
    "agendas",
    "organizadores de mesa",
    "mochilas",
    "bolsas femininas",
    "malas de viagem",
    "frasqueira",
    "necessaire",
    "porta-moedas",
    "carteira",
    "porta-cartões",
    "guarda-chuva",
    "chapéu",
    "lenço",
    "sapato social",
    "sandália",
    "sapato de salto",
    "sapato esportivo",
    "sapatilha",
    "sapato infantil",
    "macacão",
    "blusa",
    "camiseta polo",
    "calça social",
    "shorts",
    "bermuda",
    "legging",
    "agasalho",
    "jaqueta de couro",
    "sobretudo",
    "maiô",
    "biquíni",
    "sunga",
    "pijama",
    "roupão",
    "roupa íntima",
    "roupa de dormir",
    "moletom com capuz",
    "camisa de time",
    "camisa casual",
    "colete",
    "jaqueta jeans",
    "camisa polo",
    "vestido de festa",
    "saia longa",
    "saia midi",
    "blusa de frio",
    "blusa de lã",
    "blusa de seda",
    "tênis casual",
    "tênis esportivo",
    "tênis infantil",
    "perfume importado",
    "kit de maquiagem",
    "paleta de sombras",
    "batom",
    "rímel",
    "delineador",
    "base líquida",
    "corretivo",
    "pó compacto",
    "bronzer",
    "iluminador",
    "blush",
    "pincéis de maquiagem",
    "esmaltes",
    "removedor de maquiagem",
    "creme para olhos",
    "máscara capilar",
    "gel de banho",
    "esponja de banho",
    "kit de barbear",
    "cera depilatória",
    "aparador de sobrancelhas",
    "kit de viagem para cosméticos",
    "nebulizador",
    "termômetro digital",
    "oxímetro",
    "medidor de pressão arterial",
    "balança digital",
    "garrafa térmica",
    "squeeze",
    "lancheira térmica",
    "mochila escolar",
    "estojo escolar",
    "caderno universitário",
    "calculadora científica",
    "lapiseira",
    "marca-texto",
    "régua",
    "compasso",
    "agenda escolar",
    "smartwatch infantil",
    "tablet infantil",
    "kit de pintura",
    "livros infantis",
    "jogos educativos",
    "barraca infantil",
    "cama elástica",
    "toca infantil",
    "kit médico infantil",
    "carrinho de controle remoto",
    "drone infantil",
    "kit de ciência",
    "microscópio infantil",
    "telescópio infantil",
    "kit de jardinagem",
    "kit de costura",
    "kit de robótica",
    "kit de química",
    "instrumentos musicais",
    "violão",
    "guitarra",
    "bateria",
    "teclado musical",
    "piano digital",
    "ukulele",
    "flauta",
    "violino",
    "saxofone",
    "microfone profissional",
    "mesa de som",
    "caixa de som profissional",
    "amplificador",
    "pedal de guitarra",
    "acessórios musicais",
    "leitor de blu-ray",
    "soundbar",
    "receptor de TV a cabo",
    "antena parabólica",
    "controle universal",
    "smart speaker",
    "assistente virtual",
    "porta-retrato digital",
    "lâmpada inteligente",
    "interruptor inteligente",
    "fechadura digital",
    "câmera de segurança Wi-Fi",
    "campainha inteligente",
    "sensor de movimento",
    "tomada inteligente",
    "aspirador de pó inteligente",
    "balança inteligente",
    "garrafa inteligente",
    "pulseira fitness",
    "drone profissional",
    "impressora 3D",
    "scanner",
    "plotter",
    "papel fotográfico",
    "cartucho de tinta",
    "toner",
    "papel sulfite",
    "papel adesivo",
    "mouse sem fio",
    "teclado sem fio",
    "pen tablet",
    "modem",
    "switch de rede",
    "cabo de rede",
    "extensor de Wi-Fi",
    "webcam",
    "softwares",
    "antivírus",
    "licença de software",
    "serviços de streaming",
    "gift cards",
    "kits de montagem de PC",
    "cadeira ergonômica",
    "cadeira gamer",
    "suporte para monitor",
    "organizadores de cabos",
    "filtro de linha",
    "no-break",
    "leitor de código de barras",
    "maquininha de cartão",
    "protetor de tela",
    "case para notebook",
    "mochila para notebook",
    "suporte para notebook",
    "cabo USB",
    "cabo Lightning",
    "cabo Type-C",
    "adaptador de energia",
    "bateria externa",
    "fita LED",
    "kit de iluminação para fotos",
    "tripé",
    "gimbal",
    "filtro para lentes",
    "cartão de memória",
    "case para câmera",
    "drones com câmera",
    "impressora fotográfica",
    "protetor solar facial",
    "protetor solar corporal",
    "bronzeador",
    "repelente",
    "kit de viagem",
    "organizador de malas",
    "balança para bagagem",
    "travesseiro de viagem",
    "protetor auricular",
    "máscara de dormir",
    "adaptador de tomada universal",
    "garrafa de água dobrável",
    "barraca de camping",
    "saco de dormir",
    "isolante térmico",
    "lanterna",
    "fogareiro",
    "mochila de camping",
    "canivete suíço",
    "kit de sobrevivência",
    "corda de escalada",
    "cadeirinha de escalada",
    "mosquetão",
    "capacete de ciclismo",
    "joelheiras",
    "cotoveleiras",
    "óculos de proteção",
    "prancha de surf",
    "stand up paddle",
    "caiaque",
    "colete salva-vidas",
    "snorkel",
    "nadadeiras",
    "gopro",
    "suporte para câmera de ação",
    "bola de basquete",
    "bola de vôlei",
    "raquete de tênis",
    "raquete de ping-pong",
    "bolas de golfe",
    "taco de golfe",
    "taco de beisebol",
    "patins in-line",
    "slackline",
    "barraca infantil",
    "tênis de basquete",
    "tênis de skate",
    "camisa de time internacional",
    "boné de time",
    "adesivos decorativos",
    "posters",
    "action figures",
    "colecionáveis",
    "álbum de figurinhas",
    "figurinhas",
    "jogos de RPG",
    "jogos de estratégia",
    "jogos de cartas colecionáveis",
    "puzzles 3D",
    "kits de montagem",
    "modelos de aeromodelismo",
    "modelos de navios",
    "kits de pintura artística",
    "telas para pintura",
    "tintas acrílicas",
    "tintas a óleo",
    "pincéis artísticos",
    "cavalete",
    "mesa de desenho",
    "prancheta",
    "lápis de cor profissional",
    "canetas técnicas",
    "marcadores",
    "aquarelas",
    "giz pastel",
    "giz de cera",
    "massas de modelar",
    "argila",
    "rolo de pintura",
    "espátulas",
    "batedeira planetária",
    "máquina de sorvete",
    "máquina de algodão doce",
    "máquina de pipoca",
    "fonte de chocolate",
    "kit para churrasco",
    "churrasqueira elétrica",
    "churrasqueira a carvão",
    "churrasqueira a gás",
    "espeto giratório",
    "grelha",
    "acendedor elétrico",
    "tábua de corte",
    "faca de churrasco",
    "garfo trinchante",
    "copo térmico",
    "kit caipirinha",
    "copo de cerveja",
    "caneca térmica",
    "balde de gelo",
    "cooler",
    "caixa térmica",
    "sommelier",
    "aerador de vinho",
    "abridor de vinho",
    "tampa a vácuo para vinho",
    "decantador",
    "jogo de taças",
    "cafeteira espresso",
    "cápsulas de café",
    "cafeteira francesa",
    "cafeteira italiana",
    "kit de chás",
    "infusor de chá",
    "bule",
    "xícaras",
    "suporte para cápsulas",
    "moedor de café",
    "kit barista",
    "coqueteleira",
    "dosador de bebidas",
    "colher bailarina",
    "porta-rolhas",
    "kit para fondue",
    "aparelho de jantar",
    "aparelho de chá",
    "aparelho de café",
    "fruteira",
    "suqueira",
    "suporte para bolos",
    "porta-doces",
    "kit para sushi",
    "panelas de cerâmica",
    "panelas de ferro",
    "panelas antiaderentes",
    "kit de facas cerâmicas",
    "descascador",
    "ralador",
    "espremedor de batatas",
    "pipoqueira",
    "caixa de ferramentas",
    "ferramentas manuais",
    "furadeira",
    "parafusadeira",
    "serra elétrica",
    "lixadeira",
    "esmerilhadeira",
    "tupia",
    "plaina elétrica",
    "serra tico-tico",
    "multímetro",
    "soldador",
    "gerador",
    "compressores de ar",
    "lavadora de alta pressão",
    "pistola de pintura",
    "aspirador de pó industrial",
    "roçadeira",
    "motosserra",
    "cortador de grama elétrico",
    "cortador de grama a gasolina",
    "soprador de folhas",
    "aspirador de folhas",
    "mangueira de jardim",
    "regador",
    "aspersor",
    "adubos",
    "sementes",
    "ferramentas de jardinagem",
    "vasos de plantas",
    "suporte para plantas",
    "estufa",
    "luminária de plantas",
    "kit de cultivo",
    "terra vegetal",
    "piscina inflável",
    "jacuzzi",
    "banheira",
    "sauna portátil",
    "purificador de água",
    "bebedouro",
    "cadeira de praia",
    "guarda-sol",
    "esteira de praia",
    "caixa de som à prova d'água",
    "saco estanque",
    "roupa de mergulho",
    "roupa de neoprene",
    "cooler térmico",
    "kit para piquenique",
    "jogos ao ar livre",
    "badminton",
    "frescobol",
    "peteca",
    "boias",
    "colete infantil",
    "piscina infantil",
    "carrinho de bebê",
    "cadeira para auto",
    "bebê conforto",
    "banheira para bebê",
    "berço portátil",
    "cercadinho",
    "andador",
    "cadeirão",
    "babá eletrônica",
    "umidificador de ar",
    "termômetro para banho",
    "travesseiro anti-refluxo",
    "mordedor",
    "chupeta",
    "mamadeira",
    "esterilizador",
    "aquecedor de mamadeira",
    "bomba tira-leite",
    "kit higiene bebê",
    "fraldas",
    "lenços umedecidos",
    "pomada para assaduras",
    "shampoo infantil",
    "sabonete infantil",
    "protetor solar infantil",
    "brinquedos para banho",
    "tapete de atividades",
    "mobile",
    "cadeira de balanço",
    "canguru",
    "sling",
    "bolsa maternidade",
    "troca-fraldas",
    "porta-chupeta",
    "porta-mamadeira",
    "almofada de amamentação",
    "roupas para bebê",
    "macacão de bebê",
    "body",
    "conjunto de pagão",
    "sapato de bebê",
    "meias de bebê",
    "luvas de bebê",
    "touca de bebê",
    "kit berço",
    "mosquiteiro",
    "kit de segurança",
    "trava para gavetas",
    "protetor de quina",
    "capa protetora para tomadas",
    "portão de segurança",
    "grade de cama",
    "kit pintura infantil",
    "massinha de modelar",
    "livros de colorir",
    "canetinhas",
    "lápis de cor",
    "giz de cera",
    "tintas guache",
    "pincéis",
    "tesoura sem ponta",
    "cola escolar",
    "adesivos",
    "papel colorido",
    "origami",
    "álbum de fotos",
    "porta-retratos infantis",
    "decorativos de parede",
    "luminária infantil",
    "protetor de porta",
    "cabideiro infantil",
    "espelho de segurança",
    "balanço infantil",
    "escorregador",
    "gangorra",
    "cama montessoriana",
    "tapete infantil",
    "puff infantil",
    "cadeirinha de alimentação",
    "pratos infantis",
    "talheres infantis",
    "copos de treinamento",
    "babador",
    "cadeira de descanso",
    "redutor de assento sanitário",
    "penico",
    "banquinho infantil"
]

    # Dicionário para armazenar os resultados
    results = {}

    # Pesquisar produtos por tipo
    for product_type in product_types:
        search_results = requests.get(f"https://www.googleapis.com/customsearch/v1?q={product_type}&key={GOOGLE_API_KEY}&cx={cx}").json()
        products = search_results.get('items', [])
        results[product_type] = products

    # Enviar a lista de produtos para a API
    result = send_products_to_api(results, ASSISTANT_ID_GROUP)

    # Retornar a resposta em formato JSON
    return json.loads(result)

# Endpoint de pesquisa de produtos por tipo
@app.get("/search_products_by_type/")
def search_products_by_type_endpoint():
    return search_products_by_type()
